import {
  BOOLEAN_QUESTION_TYPE,
  CHECKBOXES_QUESTION_TYPE,
  DATE_QUESTION_TYPE,
  NUMBER_QUESTION_TYPE,
  RADIOBUTTONS_QUESTION_TYPE,
  SELECTBOX_QUESTION_TYPE,
  TEXT_AREA_QUESTION_TYPE,
  TEXT_FIELD_QUESTION_TYPE,
} from "@/lib/constants";
import {
  PlanAuthoringModel,
  PlanComment,
  PlanGuidanceOrgOption,
  PlanGuidanceSource,
  PlanQuestionDefinition,
  PlanSectionDefinition,
  computeProgress,
} from "../model";

// Guidance bodies are WYSIWYG-authored in the admin, so demo data deliberately
// mixes headings, links, bold/italic, lists, and blockquotes at varying lengths.
const NIH_GUIDANCE: PlanGuidanceSource = {
  id: "nih",
  label: "NIH Data Management and Sharing Policy",
  shortName: "NIH",
  orgURI: "https://ror.org/01cwqze88",
  locked: true,
  bodyHtml: [
    "<p><strong>Expectations</strong></p>",
    "<p>Describe the <em>data types, formats, standards, access controls, and preservation approach</em> for all scientific data generated by the award. Plans that only name a repository without describing curation steps are routinely returned for revision.</p>",
    "<p><strong>Elements your plan must address</strong></p>",
    "<ul><li><strong>Data type:</strong> modality, level of aggregation, and the approximate number of files or records.</li><li><strong>Related tools and software:</strong> anything a re-user needs to open or analyze the data, with versions.</li><li><strong>Standards:</strong> community metadata schemas and vocabularies; state explicitly if none exist for your field.</li><li><strong>Timelines:</strong> data should be shared no later than the associated publication, and always by the end of the award.</li></ul>",
    "<p><strong>Data sharing</strong></p>",
    "<p>Deposit into an established repository that assigns persistent identifiers. See the <a href=\"https://sharing.nih.gov/data-management-and-sharing-policy\" target=\"_blank\" rel=\"noopener\">NIH sharing policy portal</a> and the <a href=\"https://www.nlm.nih.gov/NIHbmic/domain_specific_repositories.html\" target=\"_blank\" rel=\"noopener\">list of domain-specific repositories</a> before defaulting to a generalist option.</p>",
    "<p>Institute- and Center-specific sharing policies (raw URL, deliberately long): <a href=\"https://grants.nih.gov/policy-and-compliance/policy-topics/sharing-policies/other/ics-sharing-policies\" target=\"_blank\" rel=\"noopener\">https://grants.nih.gov/policy-and-compliance/policy-topics/sharing-policies/other/ics-sharing-policies</a></p>",
    "<blockquote><p>Justified limitations on sharing (consent restrictions, tribal sovereignty, export control) are acceptable — <em>unexplained</em> limitations are not.</p></blockquote>",
    "<h3>Budget note</h3>",
    "<p>Costs of data management may be charged to the award while it is active; include them in your budget justification.</p>",
  ].join(""),
};

const UCI_GUIDANCE: PlanGuidanceSource = {
  id: "uci",
  label: "UC Irvine Research Data Guidance",
  shortName: "UCI",
  orgURI: "https://ror.org/04gyf1771",
  locked: true,
  bodyHtml: [
    "<p>Use durable, openly documented file formats wherever practical. The library maintains a <a href=\"https://guides.lib.uci.edu/datamanagement\" target=\"_blank\" rel=\"noopener\">format recommendation table</a> — when a proprietary format is unavoidable, commit to exporting an open derivative at deposit time.</p>",
    "<p><strong>Naming and organization</strong></p>",
    "<ol><li>Adopt a written file-naming convention before collection starts (date first, ISO 8601, no spaces).</li><li>Keep raw and processed data in separate, clearly labeled directories.</li><li>Record every processing step in a plain-text log stored alongside the data.</li></ol>",
    "<p><strong>Storage</strong></p>",
    "<p>Identify the <em>institutionally supported</em> storage service used during the project. Personal external drives and consumer cloud accounts are not acceptable as the primary copy. Contact <a href=\"mailto:research-data@uci.edu\">research-data@uci.edu</a> for allocations above 5&nbsp;TB.</p>",
  ].join(""),
};

const STANFORD_GUIDANCE: PlanGuidanceSource = {
  id: "stanford",
  label: "Stanford Libraries Data Management Guidance",
  shortName: "Stanford",
  orgURI: "https://ror.org/00f54p054",
  bodyHtml:
    "<p>Document metadata standards, repository selection, licensing, and any limits on access or reuse. When in doubt, <em>less restrictive licensing travels further</em> — see the <a href=\"https://library.stanford.edu/research/data-management-services\" target=\"_blank\" rel=\"noopener\">Data Management Services</a> pages for one-on-one consults.</p>",
};

// Longer Stanford variant used on some questions to exercise very tall,
// link- and list-heavy guidance in the sidebar.
const STANFORD_GUIDANCE_LONG: PlanGuidanceSource = {
  ...STANFORD_GUIDANCE,
  bodyHtml: [
    STANFORD_GUIDANCE.bodyHtml,
    "<p><strong>Repository checklist</strong></p>",
    "<ul><li>Does it issue DOIs or another persistent identifier?</li><li>Is there a published preservation policy with a named succession plan?</li><li>Can it enforce your access restrictions (embargo, click-through terms, controlled access)?</li><li>Does it export metadata in a standard schema (DataCite, ISO&nbsp;19115, Dublin&nbsp;Core)?</li></ul>",
    "<p><strong>Licensing</strong></p>",
    "<p>For most observational datasets we recommend <a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC0</a> with a citation request, falling back to <a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC&nbsp;BY&nbsp;4.0</a> when attribution must be enforceable. Software should carry an OSI-approved license (<em>MIT or Apache-2.0 are the campus defaults</em>), never a Creative Commons license.</p>",
    "<p><strong>Common pitfalls we see in review</strong></p>",
    "<ol><li>Naming a repository that has no agreement to accept the data volume described.</li><li>Promising \u201cdata available on request\u201d — this does not satisfy most funder policies.</li><li>Licensing derived data more restrictively than its sources allow.</li></ol>",
  ].join(""),
};

const guidanceCatalog: PlanGuidanceSource[] = [
  NIH_GUIDANCE,
  UCI_GUIDANCE,
  STANFORD_GUIDANCE,
];

// Variant catalog with the long Stanford body, applied to a subset of
// questions so the sidebar shows both short and very long guidance.
const richGuidanceCatalog: PlanGuidanceSource[] = [
  NIH_GUIDANCE,
  UCI_GUIDANCE,
  STANFORD_GUIDANCE_LONG,
];

const availableGuidanceOrgs: PlanGuidanceOrgOption[] = [
  {
    id: "nih",
    label: "National Institutes of Health",
    shortName: "NIH",
    orgURI: "https://ror.org/01cwqze88",
  },
  {
    id: "uci",
    label: "University of California, Irvine",
    shortName: "UCI",
    orgURI: "https://ror.org/04gyf1771",
  },
  {
    id: "stanford",
    label: "Stanford University",
    shortName: "Stanford",
    orgURI: "https://ror.org/00f54p054",
  },
  {
    id: "ucb",
    label: "UC Berkeley Research Data Program (UCB)",
    shortName: "UCB",
    orgURI: "https://berkeley.edu",
  },
  {
    id: "cdl",
    label: "California Digital Library (cdlib.org)",
    shortName: "CDL",
    orgURI: "https://cdlib.org",
  },
  {
    id: "nsf",
    label: "National Science Foundation (nsf.gov)",
    shortName: "NSF",
    orgURI: "https://nsf.gov",
  },
];

const sampleComments: PlanComment[] = [
  {
    id: 1,
    authorName: "Amelia Snow",
    createdLabel: "2 days ago",
    text: "Please quantify the expected volume for UAV imagery.",
  },
  {
    id: 2,
    authorName: "Jennifer Frost",
    createdLabel: "1 day ago",
    text: "Added approximate gigabyte ranges for each product type.",
    isFeedback: true,
  },
  {
    id: 3,
    authorName: "Amelia Snow",
    createdLabel: "4 hours ago",
    text: "Looks good — please also mention the processing pipeline.",
  },
];

function makeQuestion(
  partial: Omit<PlanQuestionDefinition, "guidanceSources" | "comments"> & {
    guidanceSources?: PlanGuidanceSource[];
    comments?: PlanComment[];
  }
): PlanQuestionDefinition {
  const { guidanceSources, comments, ...rest } = partial;
  return {
    ...rest,
    guidanceSources: guidanceSources ?? guidanceCatalog,
    comments: comments ?? [],
  };
}

export function createPlanAuthoringDemo(): PlanAuthoringModel {
  const sections: PlanSectionDefinition[] = [
    {
      identity: { kind: "base", versionedSectionId: 1 },
      title: "Products of research",
      introductionHtml:
        "<p>Describe what your project will produce — data, samples, software, and instructional materials — and clarify the nature and scale of each output.</p>",
      requirementsHtml:
        "<p>Required by funder. Reviewers expect quantitative estimates (volume, count) for every output category and a clear distinction between observational and computational data.</p>",
      displayOrder: 1,
      questions: [
        makeQuestion({
          identity: { kind: "base", versionedQuestionId: 101 },
          sectionIdentity: { kind: "base", versionedSectionId: 1 },
          title: "Primary character of data produced",
          requirementHtml:
            "<p>Select the descriptor that best reflects how the bulk of project data will be generated. This helps reviewers and repository staff understand curation expectations and influences which downstream questions are required. NSF distinguishes observational data — typically non-reproducible and requiring long-term preservation — from experimental and computational data, which can often be regenerated from documented workflows. If your project produces a mix, choose the option that covers the majority of stored volume and explain the split in the volume question below.</p>",
          required: true,
          questionType: RADIOBUTTONS_QUESTION_TYPE,
          parsedJson: {
            type: RADIOBUTTONS_QUESTION_TYPE,
            options: [
              {
                label: "Observational (sensor, field, or survey-derived)",
                value: "observational",
              },
              {
                label: "Experimental (controlled laboratory or instrument)",
                value: "experimental",
              },
              {
                label: "Computational / model-derived",
                value: "computational",
              },
              {
                label: "Mixed observational and computational",
                value: "mixed",
              },
            ],
          },
          answerJson: {
            type: RADIOBUTTONS_QUESTION_TYPE,
            answer: "mixed",
          },
          hasAnswer: true,
          guidanceSources: richGuidanceCatalog,
          comments: sampleComments,
          displayOrder: 1,
        }),
        makeQuestion({
          identity: { kind: "base", versionedQuestionId: 102 },
          sectionIdentity: { kind: "base", versionedSectionId: 1 },
          title: "Estimated volume of products",
          requirementHtml:
            "<p>Give approximate counts or storage size for each major product type.</p>",
          required: false,
          questionType: TEXT_FIELD_QUESTION_TYPE,
          parsedJson: { type: TEXT_FIELD_QUESTION_TYPE },
          answerJson: null,
          hasAnswer: false,
          comments: [
            {
              id: 11,
              authorName: "Amelia Snow",
              createdLabel: "3 days ago",
              text: "Can we estimate seasonal UAV volume separately?",
            },
          ],
          displayOrder: 2,
        }),
        makeQuestion({
          identity: { kind: "base", versionedQuestionId: 103 },
          sectionIdentity: { kind: "base", versionedSectionId: 1 },
          title: "Will products include personally identifiable information?",
          requirementHtml:
            "<p>Answer for all products combined. If any product contains PII, the access and sharing section will require a de-identification or restricted-access strategy.</p>",
          required: true,
          questionType: BOOLEAN_QUESTION_TYPE,
          parsedJson: {
            type: BOOLEAN_QUESTION_TYPE,
            attributes: { value: false },
          },
          answerJson: { type: BOOLEAN_QUESTION_TYPE, answer: false },
          hasAnswer: true,
          displayOrder: 3,
        }),
      ],
    },
    {
      identity: { kind: "base", versionedSectionId: 2 },
      title: "Data formats and standards",
      introductionHtml:
        "<p>Describe the file formats, metadata schemas, and community standards you will use so that others can understand and reuse your research products.</p>",
      requirementsHtml:
        "<p>Required by funder. Prefer open, non-proprietary formats; justify any proprietary format with a conversion or export plan.</p>",
      displayOrder: 2,
      questions: [
        makeQuestion({
          identity: { kind: "base", versionedQuestionId: 201 },
          sectionIdentity: { kind: "base", versionedSectionId: 2 },
          title: "Preferred file formats",
          requirementHtml:
            "<p>Select every format you expect to produce. Reviewers check that at least one open format is included for each data category.</p>",
          required: true,
          questionType: CHECKBOXES_QUESTION_TYPE,
          parsedJson: {
            type: CHECKBOXES_QUESTION_TYPE,
            options: [
              { label: "CSV / TSV", value: "csv" },
              { label: "NetCDF", value: "netcdf" },
              { label: "GeoTIFF", value: "geotiff" },
              { label: "JSON", value: "json" },
            ],
          },
          answerJson: {
            type: CHECKBOXES_QUESTION_TYPE,
            answer: ["csv", "netcdf"],
          },
          hasAnswer: true,
          displayOrder: 1,
        }),
        makeQuestion({
          identity: { kind: "base", versionedQuestionId: 202 },
          sectionIdentity: { kind: "base", versionedSectionId: 2 },
          title: "Primary metadata standard",
          requirementHtml:
            "<p>Choose the standard that best fits your discipline. ISO 19115 is recommended for geospatial data; DataCite is the minimum for anything receiving a DOI.</p>",
          required: false,
          questionType: SELECTBOX_QUESTION_TYPE,
          parsedJson: {
            type: SELECTBOX_QUESTION_TYPE,
            options: [
              { label: "ISO 19115", value: "iso19115" },
              { label: "Dublin Core", value: "dublin" },
              { label: "DataCite", value: "datacite" },
            ],
          },
          answerJson: null,
          hasAnswer: false,
          displayOrder: 2,
        }),
      ],
    },
    {
      identity: { kind: "base", versionedSectionId: 3 },
      title: "Access and sharing",
      introductionHtml:
        "<p>Explain how, where, and when others will be able to access your data, and describe any conditions that limit sharing.</p>",
      requirementsHtml:
        "<p>Required by funder. Data underlying publications must be available no later than the publication date; embargoes beyond 12 months need justification.</p>",
      displayOrder: 3,
      questions: [
        makeQuestion({
          identity: { kind: "base", versionedQuestionId: 301 },
          sectionIdentity: { kind: "base", versionedSectionId: 3 },
          title: "Default access level",
          requirementHtml:
            "<p>Pick the level that applies to most products. Exceptions for individual datasets can be documented in the repository record.</p>",
          required: true,
          questionType: RADIOBUTTONS_QUESTION_TYPE,
          parsedJson: {
            type: RADIOBUTTONS_QUESTION_TYPE,
            options: [
              { label: "Open", value: "open" },
              { label: "Restricted", value: "restricted" },
              { label: "Embargoed", value: "embargoed" },
            ],
          },
          answerJson: {
            type: RADIOBUTTONS_QUESTION_TYPE,
            answer: "open",
          },
          hasAnswer: true,
          guidanceSources: richGuidanceCatalog,
          displayOrder: 1,
        }),
        makeQuestion({
          identity: { kind: "custom", customQuestionId: 302 },
          sectionIdentity: { kind: "base", versionedSectionId: 3 },
          title: "Campus repository URL",
          requirementHtml:
            "<p>Provide the landing page of the campus repository collection where deposits will live. Added by your organization.</p>",
          required: false,
          questionType: TEXT_FIELD_QUESTION_TYPE,
          parsedJson: { type: TEXT_FIELD_QUESTION_TYPE },
          answerJson: {
            type: TEXT_FIELD_QUESTION_TYPE,
            answer: "https://dash.library.example.edu",
          },
          hasAnswer: true,
          displayOrder: 2,
        }),
      ],
    },
    {
      identity: { kind: "custom", customSectionId: 4 },
      title: "Retention and archive",
      introductionHtml:
        "<p>Custom section added by the organization for local retention rules. Describe how long products are kept and where they are archived after the project ends.</p>",
      requirementsHtml:
        "<p>Campus policy requires research data to be retained for a minimum of 10 years after final publication or project close-out, whichever is later.</p>",
      displayOrder: 4,
      questions: [
        makeQuestion({
          identity: { kind: "custom", customQuestionId: 401 },
          sectionIdentity: { kind: "custom", customSectionId: 4 },
          title: "Minimum retention period (years)",
          requirementHtml:
            "<p>Enter the number of years products will be retained. Campus policy sets a floor of 10 years; funder or IRB rules may extend it.</p>",
          required: true,
          questionType: NUMBER_QUESTION_TYPE,
          parsedJson: { type: NUMBER_QUESTION_TYPE },
          answerJson: { type: NUMBER_QUESTION_TYPE, answer: 10 },
          hasAnswer: true,
          displayOrder: 1,
        }),
        makeQuestion({
          identity: { kind: "custom", customQuestionId: 402 },
          sectionIdentity: { kind: "custom", customSectionId: 4 },
          title: "Archive start date",
          requirementHtml:
            "<p>Date from which the retention clock starts — usually the project end date or the date of final publication.</p>",
          required: false,
          questionType: DATE_QUESTION_TYPE,
          parsedJson: { type: DATE_QUESTION_TYPE },
          answerJson: null,
          hasAnswer: false,
          displayOrder: 2,
        }),
        makeQuestion({
          identity: { kind: "custom", customQuestionId: 403 },
          sectionIdentity: { kind: "custom", customSectionId: 4 },
          title: "Archive notes",
          required: false,
          questionType: TEXT_AREA_QUESTION_TYPE,
          parsedJson: { type: TEXT_AREA_QUESTION_TYPE },
          answerJson: null,
          hasAnswer: false,
          displayOrder: 3,
        }),
      ],
    },
    {
      identity: { kind: "base", versionedSectionId: 5 },
      title: "Roles and responsibilities",
      introductionHtml:
        "<p>Identify who is responsible for implementing this plan — during the project and after it ends — including named backups for key roles.</p>",
      requirementsHtml:
        "<p>Required by funder. Name a specific person (not just a role) for data stewardship and describe the handover process if they leave the project.</p>",
      displayOrder: 5,
      questions: [
        makeQuestion({
          identity: { kind: "base", versionedQuestionId: 501 },
          sectionIdentity: { kind: "base", versionedSectionId: 5 },
          title: "Who will manage day-to-day data stewardship?",
          requirementHtml:
            "<p>Name the person, their role on the project, and the approximate share of effort dedicated to data management tasks.</p>",
          required: true,
          questionType: TEXT_AREA_QUESTION_TYPE,
          parsedJson: { type: TEXT_AREA_QUESTION_TYPE },
          answerJson: null,
          hasAnswer: false,
          displayOrder: 1,
        }),
      ],
    },
    {
      identity: { kind: "base", versionedSectionId: 6 },
      title: "Ethics and compliance",
      introductionHtml:
        "<p>Document ethical, legal, and regulatory constraints that affect how data can be collected, stored, and shared.</p>",
      displayOrder: 6,
      questions: [
        makeQuestion({
          identity: { kind: "base", versionedQuestionId: 601 },
          sectionIdentity: { kind: "base", versionedSectionId: 6 },
          title: "Ethics review status",
          requirementHtml:
            "<p>Report the current status of your IRB or ethics board review. If pending, include the expected decision date in your stewardship notes.</p>",
          required: true,
          questionType: RADIOBUTTONS_QUESTION_TYPE,
          parsedJson: {
            type: RADIOBUTTONS_QUESTION_TYPE,
            options: [
              { label: "Not required", value: "none" },
              { label: "Pending", value: "pending" },
              { label: "Approved", value: "approved" },
            ],
          },
          answerJson: null,
          hasAnswer: false,
          displayOrder: 1,
        }),
      ],
    },
    {
      identity: { kind: "base", versionedSectionId: 7 },
      title: "Re-use and redistribution",
      introductionHtml:
        "<p>Describe the licensing and conditions under which others may re-use, remix, or redistribute your research products.</p>",
      requirementsHtml:
        "<p>Required by funder. Choose licenses no more restrictive than necessary; justify any restriction beyond attribution.</p>",
      displayOrder: 7,
      questions: [
        makeQuestion({
          identity: { kind: "base", versionedQuestionId: 701 },
          sectionIdentity: { kind: "base", versionedSectionId: 7 },
          title: "Default license for shared data",
          requirementHtml:
            "<p>Select the default license that will be applied to datasets unless a stricter license is required by IRB, partners, or sensitive content.</p>",
          required: true,
          questionType: RADIOBUTTONS_QUESTION_TYPE,
          parsedJson: {
            type: RADIOBUTTONS_QUESTION_TYPE,
            options: [
              { label: "CC0 (public domain dedication)", value: "cc0" },
              { label: "CC BY 4.0 (attribution)", value: "ccby" },
              {
                label: "CC BY-NC 4.0 (attribution, non-commercial)",
                value: "ccbync",
              },
              { label: "ODbL (open database)", value: "odbl" },
            ],
          },
          answerJson: { type: RADIOBUTTONS_QUESTION_TYPE, answer: "ccby" },
          hasAnswer: true,
          guidanceSources: richGuidanceCatalog,
          comments: [
            {
              id: 21,
              authorName: "Jennifer Frost",
              createdLabel: "5 days ago",
              text: "CC BY keeps us compatible with the repository default.",
              isFeedback: true,
            },
          ],
          displayOrder: 1,
        }),
        makeQuestion({
          identity: { kind: "base", versionedQuestionId: 702 },
          sectionIdentity: { kind: "base", versionedSectionId: 7 },
          title: "Will any products carry re-use restrictions?",
          requirementHtml:
            "<p>Answer yes if any dataset, software, or material cannot be shared under the default license above.</p>",
          required: true,
          questionType: BOOLEAN_QUESTION_TYPE,
          parsedJson: {
            type: BOOLEAN_QUESTION_TYPE,
            attributes: { value: false },
          },
          answerJson: null,
          hasAnswer: false,
          displayOrder: 2,
        }),
        makeQuestion({
          identity: { kind: "base", versionedQuestionId: 703 },
          sectionIdentity: { kind: "base", versionedSectionId: 7 },
          title: "Attribution statement",
          requirementHtml:
            "<p>Provide the citation text users must include when re-using your data (project name, grant number, DOI placeholder).</p>",
          required: false,
          questionType: TEXT_FIELD_QUESTION_TYPE,
          parsedJson: { type: TEXT_FIELD_QUESTION_TYPE },
          answerJson: {
            type: TEXT_FIELD_QUESTION_TYPE,
            answer:
              "Coastal Ocean Processes of North Greenland (NSF #2026-1234), doi:TBD",
          },
          hasAnswer: true,
          displayOrder: 3,
        }),
      ],
    },
    {
      identity: { kind: "base", versionedSectionId: 8 },
      title: "Storage and backup",
      introductionHtml:
        "<p>Describe where active project data lives, how it is backed up, and who can access working copies during the project.</p>",
      requirementsHtml:
        "<p>Required by funder. At least two geographically separate copies are expected for irreplaceable observational data.</p>",
      displayOrder: 8,
      questions: [
        makeQuestion({
          identity: { kind: "base", versionedQuestionId: 801 },
          sectionIdentity: { kind: "base", versionedSectionId: 8 },
          title: "Primary active storage service",
          requirementHtml:
            "<p>Choose the institutionally supported service that will hold the working copy of project data.</p>",
          required: true,
          questionType: SELECTBOX_QUESTION_TYPE,
          parsedJson: {
            type: SELECTBOX_QUESTION_TYPE,
            options: [
              { label: "Campus research storage (NAS)", value: "nas" },
              { label: "University cloud (Google Drive)", value: "gdrive" },
              { label: "Lab-managed server", value: "lab" },
              { label: "Commercial cloud (AWS S3)", value: "s3" },
            ],
          },
          answerJson: { type: SELECTBOX_QUESTION_TYPE, answer: "nas" },
          hasAnswer: true,
          displayOrder: 1,
        }),
        makeQuestion({
          identity: { kind: "base", versionedQuestionId: 802 },
          sectionIdentity: { kind: "base", versionedSectionId: 8 },
          title: "Backup frequency (days)",
          requirementHtml:
            "<p>Enter the maximum number of days between automated backups of active data.</p>",
          required: true,
          questionType: NUMBER_QUESTION_TYPE,
          parsedJson: { type: NUMBER_QUESTION_TYPE },
          answerJson: { type: NUMBER_QUESTION_TYPE, answer: 1 },
          hasAnswer: true,
          displayOrder: 2,
        }),
        makeQuestion({
          identity: { kind: "base", versionedQuestionId: 803 },
          sectionIdentity: { kind: "base", versionedSectionId: 8 },
          title: "Disaster recovery notes",
          requirementHtml:
            "<p>Describe how data would be restored after loss of the primary storage service, including expected recovery time.</p>",
          required: false,
          questionType: TEXT_AREA_QUESTION_TYPE,
          parsedJson: { type: TEXT_AREA_QUESTION_TYPE },
          answerJson: null,
          hasAnswer: false,
          comments: [
            {
              id: 31,
              authorName: "Amelia Snow",
              createdLabel: "6 hours ago",
              text: "IT can provide the standard DR statement for campus NAS.",
            },
          ],
          displayOrder: 3,
        }),
      ],
    },
    {
      identity: { kind: "custom", customSectionId: 9 },
      title: "Budget and resources",
      introductionHtml:
        "<p>Custom section added by the organization. Estimate the people, services, and money required to deliver this plan.</p>",
      requirementsHtml:
        "<p>Data management costs above 5% of the total budget must be itemized and pre-approved by the research office.</p>",
      displayOrder: 9,
      questions: [
        makeQuestion({
          identity: { kind: "custom", customQuestionId: 901 },
          sectionIdentity: { kind: "custom", customSectionId: 9 },
          title: "Estimated data management budget (USD)",
          requirementHtml:
            "<p>Include repository deposit fees, storage charges, and staff effort dedicated to curation.</p>",
          required: true,
          questionType: NUMBER_QUESTION_TYPE,
          parsedJson: { type: NUMBER_QUESTION_TYPE },
          answerJson: null,
          hasAnswer: false,
          displayOrder: 1,
        }),
        makeQuestion({
          identity: { kind: "custom", customQuestionId: 902 },
          sectionIdentity: { kind: "custom", customSectionId: 9 },
          title: "Which paid services will be used?",
          requirementHtml:
            "<p>Select all external services with recurring costs so the research office can track commitments.</p>",
          required: false,
          questionType: CHECKBOXES_QUESTION_TYPE,
          parsedJson: {
            type: CHECKBOXES_QUESTION_TYPE,
            options: [
              { label: "Repository deposit fees", value: "deposit" },
              { label: "Commercial cloud storage", value: "cloud" },
              { label: "Data curation contractor", value: "curation" },
              { label: "Software licenses", value: "licenses" },
            ],
          },
          answerJson: {
            type: CHECKBOXES_QUESTION_TYPE,
            answer: ["deposit", "licenses"],
          },
          hasAnswer: true,
          displayOrder: 2,
        }),
        makeQuestion({
          identity: { kind: "custom", customQuestionId: 903 },
          sectionIdentity: { kind: "custom", customSectionId: 9 },
          title: "Budget review date",
          requirementHtml:
            "<p>Date of the next research-office review of data management spending.</p>",
          required: false,
          questionType: DATE_QUESTION_TYPE,
          parsedJson: { type: DATE_QUESTION_TYPE },
          answerJson: null,
          hasAnswer: false,
          displayOrder: 3,
        }),
      ],
    },
    {
      identity: { kind: "base", versionedSectionId: 10 },
      title: "Metadata and documentation",
      introductionHtml:
        "<p>Explain how datasets will be documented so someone outside the project could understand and reuse them — READMEs, codebooks, data dictionaries, and provenance records.</p>",
      requirementsHtml:
        "<p>Required by funder. Every deposited dataset must carry machine-readable metadata plus a human-readable README describing collection methods and known limitations.</p>",
      displayOrder: 10,
      questions: [
        makeQuestion({
          identity: { kind: "base", versionedQuestionId: 1001 },
          sectionIdentity: { kind: "base", versionedSectionId: 10 },
          title: "Which documentation artifacts will accompany each dataset?",
          requirementHtml:
            "<p>Select everything that will ship with a deposit. Reviewers expect at minimum a README and a variable-level data dictionary for tabular data.</p>",
          required: true,
          questionType: CHECKBOXES_QUESTION_TYPE,
          parsedJson: {
            type: CHECKBOXES_QUESTION_TYPE,
            options: [
              { label: "README file", value: "readme" },
              { label: "Data dictionary / codebook", value: "dictionary" },
              { label: "Provenance / processing log", value: "provenance" },
              { label: "Instrument calibration records", value: "calibration" },
            ],
          },
          answerJson: {
            type: CHECKBOXES_QUESTION_TYPE,
            answer: ["readme", "dictionary"],
          },
          hasAnswer: true,
          displayOrder: 1,
        }),
        makeQuestion({
          identity: { kind: "base", versionedQuestionId: 1002 },
          sectionIdentity: { kind: "base", versionedSectionId: 10 },
          title: "Who is responsible for keeping documentation current?",
          requirementHtml:
            "<p>Name the person or role who updates READMEs and codebooks as collection protocols change during the project.</p>",
          required: false,
          questionType: TEXT_FIELD_QUESTION_TYPE,
          parsedJson: { type: TEXT_FIELD_QUESTION_TYPE },
          answerJson: null,
          hasAnswer: false,
          displayOrder: 2,
        }),
      ],
    },
    {
      identity: { kind: "base", versionedSectionId: 11 },
      title: "Data quality assurance",
      introductionHtml:
        "<p>Describe the checks that keep data trustworthy — validation rules, duplicate detection, instrument calibration, and review of manual entry.</p>",
      requirementsHtml:
        "<p>Required by funder. Describe both automated validation and human review steps, and where QA results are recorded.</p>",
      displayOrder: 11,
      questions: [
        makeQuestion({
          identity: { kind: "base", versionedQuestionId: 1101 },
          sectionIdentity: { kind: "base", versionedSectionId: 11 },
          title: "Will automated validation run on ingest?",
          requirementHtml:
            "<p>Answer yes if schema, range, or completeness checks run automatically when new data enters the working store.</p>",
          required: true,
          questionType: BOOLEAN_QUESTION_TYPE,
          parsedJson: {
            type: BOOLEAN_QUESTION_TYPE,
            attributes: { value: false },
          },
          answerJson: { type: BOOLEAN_QUESTION_TYPE, answer: true },
          hasAnswer: true,
          displayOrder: 1,
        }),
        makeQuestion({
          identity: { kind: "base", versionedQuestionId: 1102 },
          sectionIdentity: { kind: "base", versionedSectionId: 11 },
          title: "Describe the manual QA review cycle",
          requirementHtml:
            "<p>Explain how often a person reviews samples of the data, what they check, and how findings are logged and remediated.</p>",
          required: false,
          questionType: TEXT_AREA_QUESTION_TYPE,
          parsedJson: { type: TEXT_AREA_QUESTION_TYPE },
          answerJson: null,
          hasAnswer: false,
          comments: [
            {
              id: 41,
              authorName: "Amelia Snow",
              createdLabel: "1 day ago",
              text: "We should reference the cruise-report QA checklist here.",
            },
          ],
          displayOrder: 2,
        }),
      ],
    },
    {
      identity: { kind: "base", versionedSectionId: 12 },
      title: "Sensitive data and security",
      introductionHtml:
        "<p>Describe how sensitive or regulated data is protected — encryption, access control, secure enclaves, and incident response.</p>",
      requirementsHtml:
        "<p>Required by funder. Projects handling human subjects, export-controlled, or Indigenous data must document controls proportionate to risk.</p>",
      displayOrder: 12,
      questions: [
        makeQuestion({
          identity: { kind: "base", versionedQuestionId: 1201 },
          sectionIdentity: { kind: "base", versionedSectionId: 12 },
          title: "Highest data sensitivity classification",
          requirementHtml:
            "<p>Pick the most sensitive class of data the project will hold at any point, even temporarily during collection or transfer.</p>",
          required: true,
          questionType: SELECTBOX_QUESTION_TYPE,
          parsedJson: {
            type: SELECTBOX_QUESTION_TYPE,
            options: [
              { label: "Public / non-sensitive", value: "public" },
              { label: "Internal (project-only)", value: "internal" },
              { label: "Confidential (PII or partner-restricted)", value: "confidential" },
              { label: "Regulated (HIPAA, export control)", value: "regulated" },
            ],
          },
          answerJson: { type: SELECTBOX_QUESTION_TYPE, answer: "internal" },
          hasAnswer: true,
          guidanceSources: richGuidanceCatalog,
          displayOrder: 1,
        }),
        makeQuestion({
          identity: { kind: "base", versionedQuestionId: 1202 },
          sectionIdentity: { kind: "base", versionedSectionId: 12 },
          title: "Is data encrypted in transit and at rest?",
          requirementHtml:
            "<p>Answer for the primary working store and all backup copies. Field-collection devices should be covered in the notes if they differ.</p>",
          required: true,
          questionType: BOOLEAN_QUESTION_TYPE,
          parsedJson: {
            type: BOOLEAN_QUESTION_TYPE,
            attributes: { value: false },
          },
          answerJson: null,
          hasAnswer: false,
          displayOrder: 2,
        }),
        makeQuestion({
          identity: { kind: "base", versionedQuestionId: 1203 },
          sectionIdentity: { kind: "base", versionedSectionId: 12 },
          title: "Security incident contact",
          requirementHtml:
            "<p>Name and email of the person notified first if a breach or data loss involving project data is suspected.</p>",
          required: false,
          questionType: TEXT_FIELD_QUESTION_TYPE,
          parsedJson: { type: TEXT_FIELD_QUESTION_TYPE },
          answerJson: {
            type: TEXT_FIELD_QUESTION_TYPE,
            answer: "iso@example.edu (Campus Information Security Office)",
          },
          hasAnswer: true,
          displayOrder: 3,
        }),
      ],
    },
    {
      identity: { kind: "base", versionedSectionId: 13 },
      title: "Repository selection and deposit",
      introductionHtml:
        "<p>Identify the repositories where final products will be deposited and the timeline for making deposits.</p>",
      requirementsHtml:
        "<p>Required by funder. Prefer domain repositories over generalist ones; every deposit must receive a persistent identifier (DOI or equivalent).</p>",
      displayOrder: 13,
      questions: [
        makeQuestion({
          identity: { kind: "base", versionedQuestionId: 1301 },
          sectionIdentity: { kind: "base", versionedSectionId: 13 },
          title: "Primary repository for final datasets",
          requirementHtml:
            "<p>Choose the repository holding the version of record. Additional mirrors can be noted in the deposit metadata.</p>",
          required: true,
          questionType: RADIOBUTTONS_QUESTION_TYPE,
          parsedJson: {
            type: RADIOBUTTONS_QUESTION_TYPE,
            options: [
              { label: "NSF Arctic Data Center", value: "adc" },
              { label: "Dryad", value: "dryad" },
              { label: "Zenodo", value: "zenodo" },
              { label: "Campus repository (Dash)", value: "dash" },
            ],
          },
          answerJson: { type: RADIOBUTTONS_QUESTION_TYPE, answer: "adc" },
          hasAnswer: true,
          guidanceSources: richGuidanceCatalog,
          comments: [
            {
              id: 51,
              authorName: "Jennifer Frost",
              createdLabel: "2 weeks ago",
              text: "Arctic Data Center is required for NSF polar awards.",
              isFeedback: true,
            },
          ],
          displayOrder: 1,
        }),
        makeQuestion({
          identity: { kind: "base", versionedQuestionId: 1302 },
          sectionIdentity: { kind: "base", versionedSectionId: 13 },
          title: "Target date for first deposit",
          requirementHtml:
            "<p>Give the planned date of the first public deposit — usually aligned with the first data-based publication.</p>",
          required: false,
          questionType: DATE_QUESTION_TYPE,
          parsedJson: { type: DATE_QUESTION_TYPE },
          answerJson: null,
          hasAnswer: false,
          displayOrder: 2,
        }),
      ],
    },
    {
      identity: { kind: "base", versionedSectionId: 14 },
      title: "Software and code management",
      introductionHtml:
        "<p>Describe how analysis code, models, and workflows are versioned, tested, and shared alongside the data they produce.</p>",
      requirementsHtml:
        "<p>Required by funder. Code needed to reproduce published results must be archived with a persistent identifier at publication time.</p>",
      displayOrder: 14,
      questions: [
        makeQuestion({
          identity: { kind: "base", versionedQuestionId: 1401 },
          sectionIdentity: { kind: "base", versionedSectionId: 14 },
          title: "Version control platform",
          requirementHtml:
            "<p>Select where project code is hosted during development. Private repositories are fine during the project but must be archived openly at publication.</p>",
          required: true,
          questionType: SELECTBOX_QUESTION_TYPE,
          parsedJson: {
            type: SELECTBOX_QUESTION_TYPE,
            options: [
              { label: "GitHub", value: "github" },
              { label: "GitLab (campus instance)", value: "gitlab" },
              { label: "Bitbucket", value: "bitbucket" },
              { label: "Other / none", value: "other" },
            ],
          },
          answerJson: { type: SELECTBOX_QUESTION_TYPE, answer: "github" },
          hasAnswer: true,
          guidanceSources: richGuidanceCatalog,
          displayOrder: 1,
        }),
        makeQuestion({
          identity: { kind: "base", versionedQuestionId: 1402 },
          sectionIdentity: { kind: "base", versionedSectionId: 14 },
          title: "How will computational environments be captured?",
          requirementHtml:
            "<p>Describe how you will record dependencies and environments (containers, lock files, environment.yml) so analyses can be re-run years later.</p>",
          required: false,
          questionType: TEXT_AREA_QUESTION_TYPE,
          parsedJson: { type: TEXT_AREA_QUESTION_TYPE },
          answerJson: {
            type: TEXT_AREA_QUESTION_TYPE,
            answer:
              "<p>Each release is built into a Docker image; images and conda lock files are archived with the code on Zenodo.</p>",
          },
          hasAnswer: true,
          displayOrder: 2,
        }),
      ],
    },
    {
      identity: { kind: "custom", customSectionId: 15 },
      title: "Preservation and long-term access",
      introductionHtml:
        "<p>Custom section added by the organization. Explain what happens to the data after the project ends: selection for preservation, formats migration, and who pays.</p>",
      requirementsHtml:
        "<p>Campus policy: identify a named long-term steward and confirm preservation funding for at least the retention period.</p>",
      displayOrder: 15,
      questions: [
        makeQuestion({
          identity: { kind: "custom", customQuestionId: 1501 },
          sectionIdentity: { kind: "custom", customSectionId: 15 },
          title: "Which products will be preserved beyond retention?",
          requirementHtml:
            "<p>Not everything needs to be kept forever. Select the categories worth preserving after the mandated retention period expires.</p>",
          required: true,
          questionType: CHECKBOXES_QUESTION_TYPE,
          parsedJson: {
            type: CHECKBOXES_QUESTION_TYPE,
            options: [
              { label: "Raw observational data", value: "raw" },
              { label: "Processed / derived datasets", value: "derived" },
              { label: "Analysis code and workflows", value: "code" },
              { label: "Physical samples metadata", value: "samples" },
            ],
          },
          answerJson: null,
          hasAnswer: false,
          displayOrder: 1,
        }),
        makeQuestion({
          identity: { kind: "custom", customQuestionId: 1502 },
          sectionIdentity: { kind: "custom", customSectionId: 15 },
          title: "Estimated annual preservation cost (USD)",
          requirementHtml:
            "<p>Rough yearly cost of storage and curation after project close-out, for the research office's planning.</p>",
          required: false,
          questionType: NUMBER_QUESTION_TYPE,
          parsedJson: { type: NUMBER_QUESTION_TYPE },
          answerJson: { type: NUMBER_QUESTION_TYPE, answer: 1200 },
          hasAnswer: true,
          displayOrder: 2,
        }),
        makeQuestion({
          identity: { kind: "custom", customQuestionId: 1503 },
          sectionIdentity: { kind: "custom", customSectionId: 15 },
          title: "Long-term steward after project end",
          requirementHtml:
            "<p>Name the person or unit who answers access requests once the project team disbands.</p>",
          required: true,
          questionType: TEXT_FIELD_QUESTION_TYPE,
          parsedJson: { type: TEXT_FIELD_QUESTION_TYPE },
          answerJson: null,
          hasAnswer: false,
          displayOrder: 3,
        }),
      ],
    },
  ];

  return {
    title: "V4.3: Coastal Ocean Processes of North Greenland",
    templateName: "NSF GEO 2026 Template",
    affiliationName: "University of California CDL",
    templateVersion: "v1",
    funderName: "National Science Foundation (nsf.gov)",
    membersLabel: "Jennifer Frost (PI), Amelia Snow (Other)",
    relatedWorksLabel:
      "Publish your plan to start adding published outputs to your DMP.",
    progress: computeProgress(sections),
    capabilities: {
      canEditAnswers: true,
      canComment: true,
      canCustomizeGuidance: true,
      canPublish: true,
    },
    sections,
    availableGuidanceOrgs,
    selectedGuidanceOrgIds: ["nih", "uci", "stanford"],
  };
}
