query PublicPlanByDMPId($dmpId: String!) {
  publicPlanByDMPId(dmpId: $dmpId) {
    id
    title
    dmpId
    created
    modified
    registered
    visibility
    versionedTemplate {
      id
      name
      version
      owner {
        name
        displayName
        uri
        homepage
      }
    }
    project {
      title
      abstractText
      startDate
      endDate
      researchDomain {
        name
        uri
      }
    }
    members {
      id
      isPrimaryContact
      memberRoles {
        label
        uri
        id
      }
      projectMember {
        givenName
        surName
        isPrimaryContact
        orcid
      }
    }
    versions {
      modified
      dmpId
    }
    answers {
      id
      json
    }
    relatedWorks {
      id
      workVersion {
        title
        publicationDate
        workType
        publicationVenue
        sourceName
        sourceUrl
        authors {
          givenName
          surname
          full
        }
        work {
          doi
        }
      }
    }
    owner {
      id
      name
      displayName
      uri
      homepage
    }
    fundings {
      id
      projectFunding {
        grantId
        funderProjectNumber
        funderOpportunityNumber
        id
        project {
          id
        }
        status
        affiliation {
          uri
          displayName
          id
          name
        }
      }
    }
  }
}

query PublicPlanVersionByDMPId($dmpId: String!, $version: String!) {
  publicPlanVersionByDMPId(dmpId: $dmpId, version: $version) {
    isHistoricalVersion
    versionTimestamp
    dmpId
    created
    members {
      name
      orcid
      affiliationName
      isPrimaryContact
      memberRoles {
        id
        label
        uri
      }
    }
    project {
      abstractText
      endDate
      startDate
      title
      researchDomain {
        name
      }
    }
    modified
    registered
    relatedWorkIdentifiers
    title
    visibility
    owner {
      id
      name
      displayName
      uri
      homepage
    }
    answers {
      id
      json
      questionText
    }
    versionedTemplate {
      id
      title
      version
    }
    versions {
      timestamp
      url
    }
    fundings {
      funderName
      funderOpportunityNumber
      funderProjectNumber
      funderUri
      grantId
      status
    }
    relatedWorks {
      id
      workVersion {
        title
        publicationDate
        workType
        publicationVenue
        sourceName
        sourceUrl
        authors {
          givenName
          surname
          full
        }
        work {
          doi
        }
      }
    }
  }
}